export const G0_TO_G15_FACTOR = 1.2
export const NAIVE_DRIVING_SPEED = 25.9
export const WORK_WIDTH = 13.3
export const CLEARANCE_TIME_PER_TREE = 1.8
export const DOUBLE_SAWING_TIME_G0_SECONDS = 28
export const ROAD_OBSTRUCTIONS_TIME_G0_SECONDS = 15
export const DIFFICULT_PROCESSING_TIME_G0_SECONDS = 37